apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yba7ojtdj-go
  janus-idp.io/tekton: yba7ojtdj-go
  backstage.io/kubernetes-id: yba7ojtdj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yba7ojtdj-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
