apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yba7ojtdj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yba7ojtdj-go 
  name: yba7ojtdj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yba7ojtdj-go 
