apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yba7ojtdj-go 
  janus-idp.io/tekton: yba7ojtdj-go
  backstage.io/kubernetes-id: yba7ojtdj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yba7ojtdj-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml